version: '3'

volumes:
  db-data:
  node_modules:

services:
  journal-backend-api:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    container_name: journal-backend-api
    ports:
      - "5121:5121"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5121
      ConnectionStrings__JournalDBConnection: Server=mssql;Database=JournalDB;User Id=SA;Password=Password1;
    volumes:
      - ./JournalingAppBackEnd:/JournalingAppBackEnd:cached
    working_dir: /JournalingAppBackEnd
    command: dotnet watch run --no-launch-profile

  journal-frontend:
    image: node:16
    container_name: journal-frontend
    ports:
      - "4200:4200"
    environment:
      API_SERVER: http://journal-backend-api:5121
    volumes:
      - ./JournalingAppFrontEnd:/JournalingAppFrontEnd:cached
      - node_modules:/JournalingAppFrontEnd/node_modules
    working_dir: /JournalingAppFrontEnd
    command: bash -c "npm install && npx ng serve --disable-host-check --host 0.0.0.0"

  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: mssql
    environment:
      ACCEPT_EULA: y
      SA_PASSWORD: Password1
    ports:
      - 1433:1433
    volumes:
      - ./JournalingAppBackEnd/sql:/sql:cached
      - db-data:/var/opt/mssql
